// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PBCmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PB {

  /// <summary>Holder for reflection information generated from PBCmd.proto</summary>
  public static partial class PBCmdReflection {

    #region Descriptor
    /// <summary>File descriptor for PBCmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PBCmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtQQkNtZC5wcm90bxICUEIqJgoIRW5tQ21kSUQSDAoIQ1NfTE9HSU4QABIM",
            "CghTQ19MT0dJThABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PB.EnmCmdID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EnmCmdID {
    /// <summary>
    ///登录请求协议号
    /// </summary>
    [pbr::OriginalName("CS_LOGIN")] CsLogin = 0,
    /// <summary>
    ///登录请求回包协议号
    /// </summary>
    [pbr::OriginalName("SC_LOGIN")] ScLogin = 1,
  }

  #endregion

}

#endregion Designer generated code
